[project]
name = "4-sieci"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.3.5",
    "scikit-learn>=1.7.2",
    "torch>=2.9.1",
]

[dependency-groups]
dev = [
    "notebook>=7.5.0",
]
